schema = """
table name: "bigquery-public-data.crypto_near_mainnet_us.account_changes"
{
    "field name": "mode type",
    "block_date": "NULLABLE DATE, The date of the Block. Used to partition the table",
    "block_height": "NULLABLE INTEGER, The height of the Block",
    "block_timestamp": "NULLABLE INTEGER, The timestamp of the Block in nanoseconds",
    "block_timestamp_utc": "NULLABLE TIMESTAMP, The timestamp of the Block in UTC",
    "block_hash": "NULLABLE STRING, The hash of the Block",
    "chunk_hash": "NULLABLE STRING, The hash of the Chunk",
    "index_in_block": "NULLABLE INTEGER, The index in the Block",
    "affected_account_id": "NULLABLE STRING, Account ID affected by the change",
    "caused_by_transaction_hash": "NULLABLE STRING, The transaction hash that caused the change",
    "caused_by_receipt_id": "NULLABLE STRING, The receipt ID that caused the change",
    "update_reason": "NULLABLE STRING, The update reason",
    "affected_account_nonstaked_balance": "NULLABLE FLOAT, Non stacked balance",
    "affected_account_staked_balance": "NULLABLE FLOAT, Stacked balance",
    "affected_account_storage_usage": "NULLABLE FLOAT, Storage usage"
},
table name: "bigquery-public-data.crypto_near_mainnet_us.accounts"

{
  field name	mode	type	description
block_date		DATE	The date of the Block. Used to partition the table
block_height		INTEGER	The height of the Block
block_timestamp		INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc		TIMESTAMP	The timestamp of the Block in UTC
block_hash		STRING	The hash of the Block
chunk_hash		STRING	The hash of the Chunk
shard_id		INTEGER	The shard ID of the Chunk
index_in_action_receipt		INTEGER	The index in the ACTION receipt
receipt_id		STRING	An unique id for the receipt
account_id		STRING	The account ID
action_kind		STRING	The action kind: CREATE_ACCOUNT, DELETE_ACCOUNT, TRANSFER
is_active		BOOLEAN	Active Flag
}

table name: "bigquery-public-data.crypto_near_mainnet_us.blocks"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
prev_block_hash	NULLABLE	STRING	The hash of the previous Block
total_supply	NULLABLE	FLOAT	The total supply of the Block
gas_price	NULLABLE	FLOAT	The gas price of the Block
author_account_id	NULLABLE	STRING	The AccountId of the author of the Block
}

table name: "bigquery-public-data.crypto_near_mainnet_us.chunks"

{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
signature	NULLABLE	STRING	The signature of the Chunk
gas_limit	NULLABLE	FLOAT	The gas limit of the Chunk
gas_used	NULLABLE	FLOAT	The amount of gas spent on computations of the Chunk
author_account_id	NULLABLE	STRING	The AccountId of the author of the Chunk
}

table name: "bigquery-public-data.crypto_near_mainnet_us.circulating_supply"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	Block Date
computed_at_block_timestamp	NULLABLE	INTEGER	Computed at the timestamp of the Block
computed_at_block_hash	NULLABLE	STRING	Computed at the hash of the Block
computed_at_block_height	NULLABLE	INTEGER	Computed at the height of the Block
circulating_tokens_supply	NULLABLE	FLOAT	Circulating supply
total_tokens_supply	NULLABLE	FLOAT	Total supply
}

table name: "bigquery-public-data.crypto_near_mainnet_us.execution_outcomes"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
receipt_id	NULLABLE	STRING	The receipt ID
executed_in_block_hash	NULLABLE	STRING	The Block hash
outcome_receipt_ids	NULLABLE	RECORD	Receipt IDs generated by this transaction or receipt
index_in_chunk	NULLABLE	INTEGER	The index in the Chunk
gas_burnt	NULLABLE	FLOAT	The amount of the gas burnt by the given transaction or receipt
tokens_burnt	NULLABLE	FLOAT	The amount of tokens burnt corresponding to the burnt gas amount. This value does not always equal to the `gas_burnt` multiplied by the gas price, because the prepaid gas price might be lower than the actual gas price and it creates a deficit
executor_account_id	NULLABLE	STRING	The id of the account on which the execution happens. For transaction this is signer_id, for receipt this is receiver_id
status	NULLABLE	STRING	Execution status. Contains the result in case of successful execution
logs	NULLABLE	RECORD	Execution outcome logs
outcome_receipt_ids.list	REPEATED	RECORD	
outcome_receipt_ids.list.element	NULLABLE	STRING	
logs.list	REPEATED	RECORD	
logs.list.element	NULLABLE	STRING	
}

table name: "bigquery-public-data.crypto_near_mainnet_us.ft_balances_daily"{
field name	mode	type	description
epoch_date	NULLABLE	DATE	The date of the Epoch. Used to partition the table
epoch_block_height	NULLABLE	STRING	The max height of the Block in the epoch
account_id	NULLABLE	STRING	The delegator Account ID
liquid	NULLABLE	FLOAT	Liquid balance
storage_usage	NULLABLE	INTEGER	Storage Usage
unstaked_not_liquid	NULLABLE	FLOAT	Unstaked balance
staked	NULLABLE	FLOAT	Staked balance
reward	NULLABLE	FLOAT	Reward
lockup_account_id	NULLABLE	STRING	The lockup delegator Account ID
lockup_liquid	NULLABLE	FLOAT	Lockup liquid balance
lockup_unstaked_not_liquid	NULLABLE	FLOAT	Lockup unstaked balance
lockup_staked	NULLABLE	FLOAT	Lockup staked balance
lockup_reward	NULLABLE	FLOAT	Lockup Reward
}

table name: "bigquery-public-data.crypto_near_mainnet_us.ft_events"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
standard	NULLABLE	STRING	The fungible tokens standard. e.g. nep141.
receipt_id	NULLABLE	STRING	An unique id for the receipt
contract_account_id	NULLABLE	STRING	The contract account ID
affected_account_id	NULLABLE	STRING	Account ID affected by the change
involved_account_id	NULLABLE	STRING	Account ID involved
delta_amount	NULLABLE	STRING	The delta amount
cause	NULLABLE	STRING	The cause of the change
status	NULLABLE	STRING	Execution status. Contains the result in case of successful execution
event_memo	NULLABLE	STRING	The event log memo
event_index	NULLABLE	STRING	The event log index
token_id	NULLABLE	STRING	The token ID
}

table name: "bigquery-public-data.crypto_near_mainnet_us.ft_events_contracts_by_account"
{
  field name	mode	type	description
affected_account_id		STRING	
contract_account_id		STRING	
}


table name: "bigquery-public-data.crypto_near_mainnet_us.nft_events"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
standard	NULLABLE	STRING	The fungible tokens standard. e.g. nep141.
receipt_id	NULLABLE	STRING	An unique id for the receipt
contract_account_id	NULLABLE	STRING	The contract account ID
token_id	NULLABLE	STRING	The token ID
old_owner_account_id	NULLABLE	STRING	Old Owner Account ID
new_owner_account_id	NULLABLE	STRING	New Owner Account ID
authorized_account_id	NULLABLE	STRING	Authorized Account ID
cause	NULLABLE	STRING	The cause of the change
status	NULLABLE	STRING	Execution status. Contains the result in case of successful execution
event_memo	NULLABLE	STRING	The event log memo
event_index	NULLABLE	STRING	The event log index
}

table name: "bigquery-public-data.crypto_near_mainnet_us.nft_events_contracts_by_account"
{
  field name	mode	type	description
old_owner_account_id		STRING	
new_owner_account_id		STRING	
contract_account_id		STRING	
}

table name: "bigquery-public-data.crypto_near_mainnet_us.receipt_actions"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
index_in_action_receipt	NULLABLE	INTEGER	The index in the ACTION receipt
receipt_id	NULLABLE	STRING	An unique id for the receipt
gas_price	NULLABLE	STRING	The gas fee
signer_account_id	NULLABLE	STRING	An account on which behalf the origin transaction is signed
signer_public_key	NULLABLE	STRING	An access key which was used to sign the origin transaction
args	NULLABLE	STRING	Arguments
receipt_predecessor_account_id	NULLABLE	STRING	The account ID which issued a receipt. In case of a gas or deposit refund, the account ID is system
action_kind	NULLABLE	STRING	The action kind: ADD_KEY, CREATE_ACCOUNT , DELEGATE_ACTION, DELETE_ACCOUNT, DELETE_KEY, DEPLOY_CONTRACT, FUNCTION_CALL, STAKE, TRANSFER
receipt_receiver_account_id	NULLABLE	STRING	The destination account ID
is_delegate_action	NULLABLE	BOOLEAN	Flag for delegate action
}

table name: "bigquery-public-data.crypto_near_mainnet_us.receipt_details"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
index_in_chunk	NULLABLE	INTEGER	The index in the Chunk
receipt_kind	NULLABLE	STRING	There are 2 types of Receipt: ACTION and DATA. An ACTION receipt is a request to apply Actions, while a DATA receipt is a result of the application of these actions
receipt_id	NULLABLE	STRING	An unique id for the receipt
data_id	NULLABLE	STRING	An unique DATA receipt identifier
predecessor_account_id	NULLABLE	STRING	The account ID which issued a receipt. In case of a gas or deposit refund, the account ID is system
receiver_account_id	NULLABLE	STRING	The destination account ID
receipt	NULLABLE	STRING	Receipt details
}

table name: "bigquery-public-data.crypto_near_mainnet_us.receipt_origin_transaction"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
receipt_kind	NULLABLE	STRING	There are 2 types of Receipt: ACTION and DATA. An ACTION receipt is a request to apply Actions, while a DATA receipt is a result of the application of these actions
receipt_id	NULLABLE	STRING	An unique id for the receipt
data_id	NULLABLE	STRING	An unique DATA receipt identifier
originated_from_transaction_hash	NULLABLE	STRING	The transaction hash that originated the receipt
_record_last_updated_utc	NULLABLE	TIMESTAMP	
}

table name: "bigquery-public-data.crypto_near_mainnet_us.transaction_actions"
{
  field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
transaction_hash	NULLABLE	STRING	The transaction hash
transaction_status	NULLABLE	STRING	Transaction status
converted_into_receipt_id	NULLABLE	STRING	Receipt ID that the transaction was converted.
signer_account_id	NULLABLE	STRING	An account on which behalf transaction is signed
signer_public_key	NULLABLE	STRING	An access key which was used to sign a transaction
receiver_account_id	NULLABLE	STRING	Receiver account for this transaction
index_in_transaction	NULLABLE	INTEGER	The index in the transaction actions
action_kind	NULLABLE	STRING	The action kind: ADD_KEY, CREATE_ACCOUNT , DELEGATE_ACTION, DELETE_ACCOUNT, DELETE_KEY, DEPLOY_CONTRACT, FUNCTION_CALL, STAKE, TRANSFER
args	NULLABLE	STRING	Arguments
}

table name: "bigquery-public-data.crypto_near_mainnet_us.transactions"
{
field name	mode	type	description
block_date	NULLABLE	DATE	The date of the Block. Used to partition the table
block_height	NULLABLE	INTEGER	The height of the Block
block_timestamp	NULLABLE	INTEGER	The timestamp of the Block in nanoseconds
block_timestamp_utc	NULLABLE	TIMESTAMP	The timestamp of the Block in UTC
block_hash	NULLABLE	STRING	The hash of the Block
chunk_hash	NULLABLE	STRING	The hash of the Chunk
shard_id	NULLABLE	INTEGER	The shard ID of the Chunk
transaction_hash	NULLABLE	STRING	The transaction hash
index_in_chunk	NULLABLE	INTEGER	The index in the Chunk
signer_account_id	NULLABLE	STRING	An account on which behalf transaction is signed
signer_public_key	NULLABLE	STRING	An access key which was used to sign a transaction
nonce	NULLABLE	INTEGER	Nonce is used to determine order of transaction in the pool. It increments for a combination of `signer_id` and `public_key`
receiver_account_id	NULLABLE	STRING	Receiver account for this transaction
signature	NULLABLE	STRING	A signature of a hash of the Borsh-serialized Transaction
status	NULLABLE	STRING	Transaction status
converted_into_receipt_id	NULLABLE	STRING	Receipt ID that the transaction was converted.
receipt_conversion_gas_burnt	NULLABLE	INTEGER	Gas burnt in the receipt conversion
receipt_conversion_tokens_burnt	NULLABLE	FLOAT	Tokens burnt in the receipt conversion
}

"""

prompt = f'''Given an input question, first create a syntactically correct SQL query to run, 
You can order the results by a relevant column to return the most Never query for all the columns from a specific table, 
only ask for a few relevant columns given the question. 
Pay attention to use only the column names that you can see in the schema description. 
Be careful to not query for columns that do not exist. Pay attention to which column is in which table. 
DO NOT mix up the columns belonging to each table.
Also, qualify column names with the table name when needed. DO not add anything else after the query, 
just the query ONLY. NO comments, nothing. You are required to use the following format: 
SQLQuery: the SQL Query to run ;
Only use tables listed below. {schema}'''
